### ISSUE TITLE
Usage v3.0 - month filters does not work on most charts

### ISSUE THREAD

**Issue by ashwinit4d** [DalgoT4D/dbt-superset-usage#3]
v3.0 - allows to select month filter but the data for "Users onboarded for superset" or "Active Dashboards" does not change. 

[Usagev3_2.pdf](https://github.com/DalgoT4D/dbt-superset-usage/files/13265287/Usagev3_2.pdf)

[Usagev3_3.pdf](https://github.com/DalgoT4D/dbt-superset-usage/files/13267335/Usagev3_3.pdf)

**Comment by Ishankoradia** [comment]
this is fixed
